filter:
    paths: [src/*]
    excluded_paths: [bin/*, tests/*, examples/*, vendor/*]

checks:
    php:
        code_rating: true

tools:
    external_code_coverage:
        timeout: 1200
        runs: 3
    php_code_coverage: true
    php_code_sniffer:
        config:
            standard: PSR2
        filter:
            paths: ['src', 'tests']
