filter:
    paths: [src/*]
    excluded_paths: [bin/*, tests/*, examples/*, vendor/*]

checks:
    php:
        code_rating: true

tools:
    external_code_coverage:
        timeout: 1200
        runs: 3
    php_code_coverage: true
