language: php

sudo: required

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm
  fast_finish: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -qq graphviz
  - composer self-update
  - composer install --prefer-source

install:
  - travis_retry composer update $COMPOSER_OPTS

before_script:
  - mkdir -p tests/files

script:
  - ./vendor/bin/codecept run
